// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.ach.calc.validation.domain;

import java.util.Set;

privileged aspect Offender_Roo_JavaBean {
    
    public String Offender.getFirstName() {
        return this.firstName;
    }
    
    public void Offender.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String Offender.getLastName() {
        return this.lastName;
    }
    
    public void Offender.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String Offender.getSsn() {
        return this.ssn;
    }
    
    public void Offender.setSsn(String ssn) {
        this.ssn = ssn;
    }
    
    public String Offender.getTin() {
        return this.tin;
    }
    
    public void Offender.setTin(String tin) {
        this.tin = tin;
    }
    
    public OffenderAddress Offender.getAddress() {
        return this.address;
    }
    
    public void Offender.setAddress(OffenderAddress address) {
        this.address = address;
    }
    
    public Set<Long> Offender.getOffenderClaimId() {
        return this.offenderClaimId;
    }
    
    public void Offender.setOffenderClaimId(Set<Long> offenderClaimId) {
        this.offenderClaimId = offenderClaimId;
    }
    
}
