// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.ach.calc.validation.domain;

privileged aspect OffenderAddress_Roo_JavaBean {
    
    public String OffenderAddress.getAddress1() {
        return this.address1;
    }
    
    public void OffenderAddress.setAddress1(String address1) {
        this.address1 = address1;
    }
    
    public String OffenderAddress.getCity() {
        return this.city;
    }
    
    public void OffenderAddress.setCity(String city) {
        this.city = city;
    }
    
    public String OffenderAddress.getStateCode() {
        return this.stateCode;
    }
    
    public void OffenderAddress.setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    
}
