// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.ach.calc.validation.domain;

import com.bfds.ach.calc.validation.domain.ValidationResult;

privileged aspect ValidationResult_Roo_JavaBean {
    
    public Long ValidationResult.getId() {
        return this.id;
    }
    
    public void ValidationResult.setId(Long id) {
        this.id = id;
    }
    
    public Long ValidationResult.getClaimantClaimId() {
        return this.claimantClaimId;
    }
    
    public void ValidationResult.setClaimantClaimId(Long claimantClaimId) {
        this.claimantClaimId = claimantClaimId;
    }
    
    public String ValidationResult.getValidationType() {
        return this.validationType;
    }
    
    public void ValidationResult.setValidationType(String validationType) {
        this.validationType = validationType;
    }
    
    public String ValidationResult.getStatus() {
        return this.status;
    }
    
    public void ValidationResult.setStatus(String status) {
        this.status = status;
    }
    
    public String ValidationResult.getComments() {
        return this.comments;
    }
    
    public void ValidationResult.setComments(String comments) {
        this.comments = comments;
    }
    
}
